
[default.extend-words]
# words that should not be corrected
O957 = "O957"
Soler = "Soler"
dot_acn = ".acn"
dot_fot = ".fot"
dot_ist = ".ist"
MERCHANTIBILITY = "MERCHANTIBILITY"

[files]
extend-exclude = [
    ".gitignore",
    ".pre-commit-config.yaml",
    "./.github/ISSUE_TEMPLATE/*.md"]
